layout_spectrum: 0.1545059101190418
typography_spectrum: 0.6274519504513592
color:
  brandStrength: 0.8110639890655875
  lightness: 0.4115989147685468
  saturation: 0.20122157339937985
  rhythmicContrast: 0.06749892234802246
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Stockport CCTV
navigation:
  - id: 'http://stockportcctv.co.uk/index.html'
    url: 'http://stockportcctv.co.uk/index.html'
    name: Home
    type: external
  - id: 'http://stockportcctv.co.uk/about-us.html'
    url: 'http://stockportcctv.co.uk/about-us.html'
    name: About Us
    type: external
  - id: 'http://stockportcctv.co.uk/cameras.html'
    url: 'http://stockportcctv.co.uk/cameras.html'
    name: Cameras
    type: external
