typography_spectrum: 0.6274519504513592
color:
  brandStrength: 0.8110639890655875
  lightness: 0.4115989147685468
  saturation: 0.20122157339937985
  rhythmicContrast: 0.06749892234802246
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/008d7717-5509-440a-af5c-777f625149bf.jpg
layout_spectrum: 0.1545059101190418
author:
  name: Stuart G
  email: stu@stockportcctv.co.uk
  url: 'http://stockportcctv.co.uk'
name: Stockport CCTV
navigation:
  - name: Home
    url: 'http://stockportcctv.co.uk/index.html'
    type: external
  - name: About Us
    url: 'http://stockportcctv.co.uk/about-us.html'
    type: external
  - name: Cameras
    url: 'http://stockportcctv.co.uk/cameras.html'
    type: external
  - name: Testimonials
    url: 'http://stockportcctv.co.uk/testimonials.html'
    type: external
  - name: Contact Us
    url: 'http://stockportcctv.co.uk/contact-us.html'
    type: external
title: STOCKPORT CCTV
